name: Hello world

on: 
  push:
    branches: ["gh-pages"]
  pull_request:
    branches: ["gh-pages"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: print hello world
        run: echo "hello world"
